CREATE DATABASE EMP_1;
CREATE TABLE EMP_1(field_name CHAR(15), Data_Declaration VARCHAR(18));
INSERT INTO EMP_1 VALUE('EMP_NUM', 'CHAR(3)');
INSERT INTO EMP_1 VALUE('EMP_Lname', 'VARCHAR(15)');
INSERT INTO EMP_1 VALUE('EMP_FNAME', 'VARCHAR(15)');
INSERT INTO EMP_1 VALUE('EMP_INITIAL', 'CHAR(1)');
INSERT INTO EMP_1 VALUE('EMP_HIREDATE', 'DATE');
INSERT INTO EMP_1 VALUE('JOB_CODE', 'CHAR(3)');