CREATE DATABASE EXERCISE_1;
CREATE TABLE EMP_1(
	EMP_NUM CHAR(3) NOT NULL,
	EMP_LNAME CHAR(15),
	EMP_FNAME VARCHAR(15),
	EMP_INITIAL CHAR(1), 
	EMP_HIREDATE DATE,
	JOB_CODE CHAR(3), 
 PRIMARY KEY (EMP_NUM));
 
 INSERT INTO EMP_1(EMP_NUM, EMP_LNAME, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE)
 VALUE('1', 'IGNACIO', 'PRINCE DAVE', 'S', '2023-03-28', '501');
 INSERT INTO EMP_1(EMP_NUM, EMP_LNAME, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE)
 VALUE('2', 'AGUSTINE', 'ALVIN', 'V', '2023-04-28', '502');
 INSERT INTO EMP_1(EMP_NUM, EMP_LNAME, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE)
 VALUE('3', 'GALAHAN', 'ALEXINE', 'C', '2023-05-28', '503');
 
 SELECT EMP_NUM, EMP_LNAME, EMP_FNAME, EMP_INITIAL, EMP_HIREDATE, JOB_CODE FROM EMP_1 WHERE EMP_NUM = 2 ;